//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PMSEntities : DbContext
    {
        public PMSEntities()
            : base("name=PMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
    
        public virtual int PMS_Project(Nullable<int> actionId, Nullable<int> projId, string projectName, string projectDescription, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> projectManagerId, Nullable<int> projectStatus, Nullable<int> createdBy, Nullable<int> modifyBy)
        {
            var actionIdParameter = actionId.HasValue ?
                new ObjectParameter("ActionId", actionId) :
                new ObjectParameter("ActionId", typeof(int));
    
            var projIdParameter = projId.HasValue ?
                new ObjectParameter("ProjId", projId) :
                new ObjectParameter("ProjId", typeof(int));
    
            var projectNameParameter = projectName != null ?
                new ObjectParameter("ProjectName", projectName) :
                new ObjectParameter("ProjectName", typeof(string));
    
            var projectDescriptionParameter = projectDescription != null ?
                new ObjectParameter("projectDescription", projectDescription) :
                new ObjectParameter("projectDescription", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var projectManagerIdParameter = projectManagerId.HasValue ?
                new ObjectParameter("ProjectManagerId", projectManagerId) :
                new ObjectParameter("ProjectManagerId", typeof(int));
    
            var projectStatusParameter = projectStatus.HasValue ?
                new ObjectParameter("ProjectStatus", projectStatus) :
                new ObjectParameter("ProjectStatus", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            var modifyByParameter = modifyBy.HasValue ?
                new ObjectParameter("ModifyBy", modifyBy) :
                new ObjectParameter("ModifyBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PMS_Project", actionIdParameter, projIdParameter, projectNameParameter, projectDescriptionParameter, startDateParameter, endDateParameter, projectManagerIdParameter, projectStatusParameter, createdByParameter, modifyByParameter);
        }
    }
}
